version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: db            # Use 'db' as the database name, as configured in your application.properties
    ports:
      - "3306:3306"
    volumes:
      - mysql_db:/var/lib/mysql   # Persistent volume for MySQL data

  backend:
    image: ayhem42/tp-foyer:latest  # Replace with your built Spring Boot Docker image
    restart: on-failure
    depends_on:
      - mysql
    ports:
      - "8089:8089"                 # Matches the server.port in application.properties
    environment:
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - backend_logs:/app/logs      # Optional volume for backend logs

volumes:
  mysql_db:
  backend_logs:
