
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: kaddem-app:1.1.4
    container_name: kaddem-app
    ports:
      - "9055:9055"
    depends_on:
      - db
    command: ["java", "-jar", "/app/kaddem-1.1.4.jar"]
    
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: kaddemdb
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
