version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD:


    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    image: chaimasassi/tp-foyer:latest  # Make sure this image tag is correct
    restart: on-failure
    depends_on :
      - db
    ports:
      - "8083:8083"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/tp_foyer_db?createDatabaseIfNotExist=true

      SPRING_DATASOURCE_PASSWORD:
      SPRING_SERVER_PORT: 8083

volumes:
  db_data: