version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql_container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Sassii260994
      MYSQL_DATABASE: tp_foyer_db
      MYSQL_USER: chaimasassi
      MYSQL_PASSWORD: Sassii260994
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    image: chaimasassi/tp-foyer:latest  # Make sure this image tag is correct
    container_name: app_container
    restart: on-failure
    ports:
      - "8083:8083"
    
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/tp_foyer_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: chaimasassi
      SPRING_DATASOURCE_PASSWORD: Sassii260994
      SPRING_SERVER_PORT: 8083

volumes:
  db_data: